language: go
go:
  - 1.4 
install:
  - go get github.com/constabulary/gb/...
script:
  - gb build
deploy:
  provider: releases
  api_key:
    secure: U+U3g/JRtclq2ZAfnRmhtnABJugMrl9VfGB+/8OOQYHuhckdtquP4mbahFO1AJ1xF0huRwRD29lyi9/jYwmCQbC9Spx2pVrLP0go1geLIqqkxcMbt4MlNMVfqLN+YjaPgbKKAhK9g1SeoRBlDFxIvIMKFgG4/VVPAAoZ40HLL0E=
  file: bin/dbsync
  on:
    repo: allermedia/dbsync
